name: flutter_timer
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  equatable: ^2.0.3
  bloc : ^8.1.0
  flutter:
    sdk: flutter

  flutter_bloc : ^8.1.1

dev_dependencies:
  bloc_test : ^9.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail : ^1.0.0

flutter:
  uses-material-design: true
